# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :app_distrubution do
    sh "flutter clean"
    sh "flutter build apk --release"
    firebase_app_distribution(
      app: "1:406408892526:android:6bd338f7c11b3f6e0b567f",
      firebase_cli_token: "1//03sLkLohGDRWSCgYIARAAGAMSNwF-L9IrHPvr1Bp4WywskcMmxl7wrqhvLIOtBO4viMxkQxm9PKAjcHhVtw23NrrFVbACcCfQ8pA",
      android_artifact_type: "APK",
      android_artifact_path: "../build/app/outputs/flutter-apk/app-release.apk",
      testers: "m7amedking112@gmail.com, shehabehab1029@gmail.com",
      release_notes: "First apk distribution with fastlane"
    )

  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
